In [3]:
from dbrepo.RestClient import RestClient

client = RestClient(
    endpoint="https://test.dbrepo.tuwien.ac.at",
    username="gokayyil",
    password="123123Go."
)

print(client.whoami())

gokayyil
gokayyil

In [4]:
DATABASE_ID = "a6229b2e-5a3d-4a46-93aa-e9474f492ec1"

database = client.get_database(DATABASE_ID)

print(database)

id='a6229b2e-5a3d-4a46-93aa-e9474f492ec1' name='coffee_productivity_prediction' exchange_name='dbrepo' internal_name='coffee_productivity_prediction_wbmm' is_public=False is_schema_public=False is_dashboard_enabled=False container=ContainerBrief(id='6cfb3b8e-1792-4e46-871a-f3d103527203', name='mariadb-galera:11.3.2', image=ImageBrief(id='d79cb089-363c-488b-9717-649e44d8fcc5', name='mariadb', version='11.1.3', default=False), internal_name='mariadb_11_3_2', running=None, hash=None) owner=UserBrief(username='gokayyil', id=None, name=None, orcid=None, qualified_name=None, given_name=None, family_name=None) contact=UserBrief(username='gokayyil', id=None, name=None, orcid=None, qualified_name=None, given_name=None, family_name=None) identifiers=[] subsets=[] tables=[Table(id='9abc69b3-932e-4a20-93a6-9e3cb4ac9676', database_id='a6229b2e-5a3d-4a46-93aa-e9474f492ec1', name='health_metrics', owner=UserBrief(username='gokayyil', id=None, name=None, orcid=None, qualified_name=None, given_name=None, family_name=None), columns=[Column(id='ff8a6b23-c905-4330-96ea-1d8ca2619ee0', name='participant_id', database_id='a6229b2e-5a3d-4a46-93aa-e9474f492ec1', table_id='9abc69b3-932e-4a20-93a6-9e3cb4ac9676', ord=0, internal_name='participant_id', is_null_allowed=False, type=<ColumnType.BIGINT: 'bigint'>, alias=None, description=None, size=None, d=None, mean=50.5, median=50.5, concept=None, unit=None, concept_uri=None, unit_uri=None, enums=[], sets=[], index_length=None, length=None, data_length=None, max_data_length=None, num_rows=None, val_min=None, val_max=None, std_dev=28.8661), Column(id='57182a37-055a-4a39-84e5-6b7b6729943c', name='bmi', database_id='a6229b2e-5a3d-4a46-93aa-e9474f492ec1', table_id='9abc69b3-932e-4a20-93a6-9e3cb4ac9676', ord=1, internal_name='bmi', is_null_allowed=False, type=<ColumnType.DECIMAL: 'decimal'>, alias=None, description=None, size=40, d=20, mean=23.239, median=23.239, concept=None, unit=None, concept_uri=None, unit_uri=None, enums=[], sets=[], index_length=None, length=None, data_length=None, max_data_length=None, num_rows=None, val_min=None, val_max=None, std_dev=4.2094), Column(id='d70581d8-2436-4410-9ce7-eb6dea905b18', name='heart_rate_bpm', database_id='a6229b2e-5a3d-4a46-93aa-e9474f492ec1', table_id='9abc69b3-932e-4a20-93a6-9e3cb4ac9676', ord=2, internal_name='heart_rate_bpm', is_null_allowed=False, type=<ColumnType.BIGINT: 'bigint'>, alias=None, description=None, size=None, d=None, mean=70.3, median=70.3, concept=None, unit=None, concept_uri=None, unit_uri=None, enums=[], sets=[], index_length=None, length=None, data_length=None, max_data_length=None, num_rows=None, val_min=None, val_max=None, std_dev=9.376), Column(id='ad57b8a8-146c-44be-92f4-8a921519ac60', name='health_issues', database_id='a6229b2e-5a3d-4a46-93aa-e9474f492ec1', table_id='9abc69b3-932e-4a20-93a6-9e3cb4ac9676', ord=3, internal_name='health_issues', is_null_allowed=False, type=<ColumnType.TEXT: 'text'>, alias=None, description=None, size=None, d=None, mean=4.16, median=4.16, concept=None, unit=None, concept_uri=None, unit_uri=None, enums=[], sets=[], index_length=None, length=None, data_length=None, max_data_length=None, num_rows=None, val_min=None, val_max=None, std_dev=0.7838)], constraints=Constraints(uniques=[], foreign_keys=[], checks=[], primary_key=[PrimaryKey(id='afb6c36f-02ea-4b5d-9a02-a87b498068dd', table=TableBrief(id='9abc69b3-932e-4a20-93a6-9e3cb4ac9676', database_id='a6229b2e-5a3d-4a46-93aa-e9474f492ec1', name='health_metrics', description='Table containing BMI, heart rate, and reported health issue category.', internal_name='health_metrics', is_versioned=True, is_public=True, is_schema_public=True, owned_by='gokayyil'), column=ColumnBrief(id='ff8a6b23-c905-4330-96ea-1d8ca2619ee0', name='participant_id', database_id='a6229b2e-5a3d-4a46-93aa-e9474f492ec1', table_id='9abc69b3-932e-4a20-93a6-9e3cb4ac9676', internal_name='participant_id', type=<ColumnType.BIGINT: 'bigint'>, alias=None))]), internal_name='health_metrics', is_versioned=True, queue_name='dbrepo', routing_key='dbrepo.a6229b2e-5a3d-4a46-93aa-e9474f492ec1.9abc69b3-932e-4a20-93a6-9e3cb4ac9676', is_public=True, is_schema_public=True, identifiers=[], description='Table containing BMI, heart rate, and reported health issue category.', queue_type='quorum', num_rows=100, data_length=16384, max_data_length=0, avg_row_length=163), Table(id='dddb6b09-ba3f-4003-bf93-73786410e886', database_id='a6229b2e-5a3d-4a46-93aa-e9474f492ec1', name='lifestyle_metrics', owner=UserBrief(username='gokayyil', id=None, name=None, orcid=None, qualified_name=None, given_name=None, family_name=None), columns=[Column(id='bcd68c6c-63b8-4774-97cd-dcae2f006ff6', name='participant_id', database_id='a6229b2e-5a3d-4a46-93aa-e9474f492ec1', table_id='dddb6b09-ba3f-4003-bf93-73786410e886', ord=0, internal_name='participant_id', is_null_allowed=False, type=<ColumnType.BIGINT: 'bigint'>, alias=None, description=None, size=None, d=None, mean=50.5, median=50.5, concept=None, unit=None, concept_uri=None, unit_uri=None, enums=[], sets=[], index_length=None, length=None, data_length=None, max_data_length=None, num_rows=None, val_min=None, val_max=None, std_dev=28.8661), Column(id='52e33311-e40d-49e2-8cef-9fd8f8afa76d', name='stress_level', database_id='a6229b2e-5a3d-4a46-93aa-e9474f492ec1', table_id='dddb6b09-ba3f-4003-bf93-73786410e886', ord=1, internal_name='stress_level', is_null_allowed=False, type=<ColumnType.TEXT: 'text'>, alias=None, description=None, size=None, d=None, mean=3.54, median=3.54, concept=None, unit=None, concept_uri=None, unit_uri=None, enums=[], sets=[], index_length=None, length=None, data_length=None, max_data_length=None, num_rows=None, val_min=None, val_max=None, std_dev=1.0993), Column(id='49a0379f-dc64-48be-b0a3-21056dcab329', name='physical_activity_hours', database_id='a6229b2e-5a3d-4a46-93aa-e9474f492ec1', table_id='dddb6b09-ba3f-4003-bf93-73786410e886', ord=2, internal_name='physical_activity_hours', is_null_allowed=False, type=<ColumnType.DECIMAL: 'decimal'>, alias=None, description=None, size=40, d=20, mean=7.868, median=7.868, concept=None, unit=None, concept_uri=None, unit_uri=None, enums=[], sets=[], index_length=None, length=None, data_length=None, max_data_length=None, num_rows=None, val_min=None, val_max=None, std_dev=4.1667), Column(id='bdd0b95f-e4f1-41ac-ab26-79d0b7c9ee7b', name='smoking', database_id='a6229b2e-5a3d-4a46-93aa-e9474f492ec1', table_id='dddb6b09-ba3f-4003-bf93-73786410e886', ord=3, internal_name='smoking', is_null_allowed=False, type=<ColumnType.BOOL: 'bool'>, alias=None, description=None, size=None, d=None, mean=0.23, median=0.23, concept=None, unit=None, concept_uri=None, unit_uri=None, enums=[], sets=[], index_length=None, length=None, data_length=None, max_data_length=None, num_rows=None, val_min=None, val_max=None, std_dev=0.4208), Column(id='2f8086e1-d73b-4358-9ef8-e87d1b4bebae', name='alcohol_consumption', database_id='a6229b2e-5a3d-4a46-93aa-e9474f492ec1', table_id='dddb6b09-ba3f-4003-bf93-73786410e886', ord=4, internal_name='alcohol_consumption', is_null_allowed=False, type=<ColumnType.BOOL: 'bool'>, alias=None, description=None, size=None, d=None, mean=0.27, median=0.27, concept=None, unit=None, concept_uri=None, unit_uri=None, enums=[], sets=[], index_length=None, length=None, data_length=None, max_data_length=None, num_rows=None, val_min=None, val_max=None, std_dev=0.444)], constraints=Constraints(uniques=[], foreign_keys=[], checks=[], primary_key=[PrimaryKey(id='c9ae6b9a-c6f1-4765-9c3b-05f9833d1e00', table=TableBrief(id='dddb6b09-ba3f-4003-bf93-73786410e886', database_id='a6229b2e-5a3d-4a46-93aa-e9474f492ec1', name='lifestyle_metrics', description='Table containing stress level, physical activity duration, smoking status, and alcohol consumption status.', internal_name='lifestyle_metrics', is_versioned=True, is_public=True, is_schema_public=True, owned_by='gokayyil'), column=ColumnBrief(id='bcd68c6c-63b8-4774-97cd-dcae2f006ff6', name='participant_id', database_id='a6229b2e-5a3d-4a46-93aa-e9474f492ec1', table_id='dddb6b09-ba3f-4003-bf93-73786410e886', internal_name='participant_id', type=<ColumnType.BIGINT: 'bigint'>, alias=None))]), internal_name='lifestyle_metrics', is_versioned=True, queue_name='dbrepo', routing_key='dbrepo.a6229b2e-5a3d-4a46-93aa-e9474f492ec1.dddb6b09-ba3f-4003-bf93-73786410e886', is_public=True, is_schema_public=True, identifiers=[], description='Table containing stress level, physical activity duration, smoking status, and alcohol consumption status.', queue_type='quorum', num_rows=100, data_length=16384, max_data_length=0, avg_row_length=163), Table(id='6e828acb-4698-4f34-9a62-1a753b768554', database_id='a6229b2e-5a3d-4a46-93aa-e9474f492ec1', name='coffee_consumption', owner=UserBrief(username='gokayyil', id=None, name=None, orcid=None, qualified_name=None, given_name=None, family_name=None), columns=[Column(id='ea78c4ce-44da-4468-b4d7-3880baf9b1e1', name='participant_id', database_id='a6229b2e-5a3d-4a46-93aa-e9474f492ec1', table_id='6e828acb-4698-4f34-9a62-1a753b768554', ord=0, internal_name='participant_id', is_null_allowed=False, type=<ColumnType.BIGINT: 'bigint'>, alias=None, description=None, size=None, d=None, mean=50.5, median=50.5, concept=None, unit=None, concept_uri=None, unit_uri=None, enums=[], sets=[], index_length=None, length=None, data_length=None, max_data_length=None, num_rows=None, val_min=None, val_max=None, std_dev=28.8661), Column(id='d3cf2175-5393-43d6-8707-31a39be698b4', name='coffee_intake_cups_per_day', database_id='a6229b2e-5a3d-4a46-93aa-e9474f492ec1', table_id='6e828acb-4698-4f34-9a62-1a753b768554', ord=1, internal_name='coffee_intake_cups_per_day', is_null_allowed=False, type=<ColumnType.DECIMAL: 'decimal'>, alias=None, description=None, size=40, d=20, mean=2.363, median=2.363, concept=None, unit=None, concept_uri=None, unit_uri=None, enums=[], sets=[], index_length=None, length=None, data_length=None, max_data_length=None, num_rows=None, val_min=None, val_max=None, std_dev=1.3713), Column(id='f5f80e8f-af51-4961-bf4d-7ff65264aa6b', name='caffeine_mg_per_day', database_id='a6229b2e-5a3d-4a46-93aa-e9474f492ec1', table_id='6e828acb-4698-4f34-9a62-1a753b768554', ord=2, internal_name='caffeine_mg_per_day', is_null_allowed=False, type=<ColumnType.DECIMAL: 'decimal'>, alias=None, description=None, size=40, d=20, mean=224.407, median=224.407, concept=None, unit=None, concept_uri=None, unit_uri=None, enums=[], sets=[], index_length=None, length=None, data_length=None, max_data_length=None, num_rows=None, val_min=None, val_max=None, std_dev=130.0596)], constraints=Constraints(uniques=[], foreign_keys=[], checks=[], primary_key=[PrimaryKey(id='a5cc08a3-7f36-4a92-8ec5-91fd99a92191', table=TableBrief(id='6e828acb-4698-4f34-9a62-1a753b768554', database_id='a6229b2e-5a3d-4a46-93aa-e9474f492ec1', name='coffee_consumption', description='Table containing daily coffee intake in cups and daily caffeine intake in milligrams.', internal_name='coffee_consumption', is_versioned=True, is_public=True, is_schema_public=True, owned_by='gokayyil'), column=ColumnBrief(id='ea78c4ce-44da-4468-b4d7-3880baf9b1e1', name='participant_id', database_id='a6229b2e-5a3d-4a46-93aa-e9474f492ec1', table_id='6e828acb-4698-4f34-9a62-1a753b768554', internal_name='participant_id', type=<ColumnType.BIGINT: 'bigint'>, alias=None))]), internal_name='coffee_consumption', is_versioned=True, queue_name='dbrepo', routing_key='dbrepo.a6229b2e-5a3d-4a46-93aa-e9474f492ec1.6e828acb-4698-4f34-9a62-1a753b768554', is_public=True, is_schema_public=True, identifiers=[], description='Table containing daily coffee intake in cups and daily caffeine intake in milligrams.', queue_type='quorum', num_rows=100, data_length=16384, max_data_length=0, avg_row_length=163), Table(id='83a691e2-a7ad-4b5a-b468-03c3d63d727b', database_id='a6229b2e-5a3d-4a46-93aa-e9474f492ec1', name='sleep_metrics', owner=UserBrief(username='gokayyil', id=None, name=None, orcid=None, qualified_name=None, given_name=None, family_name=None), columns=[Column(id='26c1d10d-9751-4df2-8816-039d35e65d00', name='participant_id', database_id='a6229b2e-5a3d-4a46-93aa-e9474f492ec1', table_id='83a691e2-a7ad-4b5a-b468-03c3d63d727b', ord=0, internal_name='participant_id', is_null_allowed=False, type=<ColumnType.BIGINT: 'bigint'>, alias=None, description=None, size=None, d=None, mean=50.5, median=50.5, concept=None, unit=None, concept_uri=None, unit_uri=None, enums=[], sets=[], index_length=None, length=None, data_length=None, max_data_length=None, num_rows=None, val_min=None, val_max=None, std_dev=28.8661), Column(id='90dfad3a-4f42-4195-b611-33c45afcb1d1', name='sleep_hours', database_id='a6229b2e-5a3d-4a46-93aa-e9474f492ec1', table_id='83a691e2-a7ad-4b5a-b468-03c3d63d727b', ord=1, internal_name='sleep_hours', is_null_allowed=False, type=<ColumnType.DECIMAL: 'decimal'>, alias=None, description=None, size=40, d=20, mean=6.742, median=6.742, concept=None, unit=None, concept_uri=None, unit_uri=None, enums=[], sets=[], index_length=None, length=None, data_length=None, max_data_length=None, num_rows=None, val_min=None, val_max=None, std_dev=1.0433), Column(id='04efe6b6-5237-403e-9600-4531306a050d', name='sleep_quality', database_id='a6229b2e-5a3d-4a46-93aa-e9474f492ec1', table_id='83a691e2-a7ad-4b5a-b468-03c3d63d727b', ord=2, internal_name='sleep_quality', is_null_allowed=False, type=<ColumnType.TEXT: 'text'>, alias=None, description=None, size=None, d=None, mean=4.5, median=4.5, concept=None, unit=None, concept_uri=None, unit_uri=None, enums=[], sets=[], index_length=None, length=None, data_length=None, max_data_length=None, num_rows=None, val_min=None, val_max=None, std_dev=1.5)], constraints=Constraints(uniques=[], foreign_keys=[], checks=[], primary_key=[PrimaryKey(id='3d3d34b2-0999-48bb-974e-87c1c448607c', table=TableBrief(id='83a691e2-a7ad-4b5a-b468-03c3d63d727b', database_id='a6229b2e-5a3d-4a46-93aa-e9474f492ec1', name='sleep_metrics', description='Table containing sleep duration and sleep quality information.', internal_name='sleep_metrics', is_versioned=True, is_public=True, is_schema_public=True, owned_by='gokayyil'), column=ColumnBrief(id='26c1d10d-9751-4df2-8816-039d35e65d00', name='participant_id', database_id='a6229b2e-5a3d-4a46-93aa-e9474f492ec1', table_id='83a691e2-a7ad-4b5a-b468-03c3d63d727b', internal_name='participant_id', type=<ColumnType.BIGINT: 'bigint'>, alias=None))]), internal_name='sleep_metrics', is_versioned=True, queue_name='dbrepo', routing_key='dbrepo.a6229b2e-5a3d-4a46-93aa-e9474f492ec1.83a691e2-a7ad-4b5a-b468-03c3d63d727b', is_public=True, is_schema_public=True, identifiers=[], description='Table containing sleep duration and sleep quality information.', queue_type='quorum', num_rows=100, data_length=16384, max_data_length=0, avg_row_length=163), Table(id='913c5c1d-3e46-4393-9e5e-744ab04e0ad2', database_id='a6229b2e-5a3d-4a46-93aa-e9474f492ec1', name='participants', owner=UserBrief(username='gokayyil', id=None, name=None, orcid=None, qualified_name=None, given_name=None, family_name=None), columns=[Column(id='fc7636e8-1850-432b-ad5d-996a338b7ad1', name='participant_id', database_id='a6229b2e-5a3d-4a46-93aa-e9474f492ec1', table_id='913c5c1d-3e46-4393-9e5e-744ab04e0ad2', ord=0, internal_name='participant_id', is_null_allowed=False, type=<ColumnType.BIGINT: 'bigint'>, alias=None, description=None, size=None, d=None, mean=50.5, median=50.5, concept=None, unit=None, concept_uri=None, unit_uri=None, enums=[], sets=[], index_length=None, length=None, data_length=None, max_data_length=None, num_rows=None, val_min=None, val_max=None, std_dev=28.8661), Column(id='7c66c820-ea1c-46f6-8582-a5ce3415788c', name='age', database_id='a6229b2e-5a3d-4a46-93aa-e9474f492ec1', table_id='913c5c1d-3e46-4393-9e5e-744ab04e0ad2', ord=1, internal_name='age', is_null_allowed=False, type=<ColumnType.BIGINT: 'bigint'>, alias=None, description=None, size=None, d=None, mean=33.75, median=33.75, concept=None, unit=None, concept_uri=None, unit_uri=None, enums=[], sets=[], index_length=None, length=None, data_length=None, max_data_length=None, num_rows=None, val_min=None, val_max=None, std_dev=9.9059), Column(id='307909e1-d29b-4ba9-981a-ebfd50b96438', name='gender_id', database_id='a6229b2e-5a3d-4a46-93aa-e9474f492ec1', table_id='913c5c1d-3e46-4393-9e5e-744ab04e0ad2', ord=2, internal_name='gender_id', is_null_allowed=False, type=<ColumnType.BIGINT: 'bigint'>, alias=None, description=None, size=None, d=None, mean=1.49, median=1.49, concept=None, unit=None, concept_uri=None, unit_uri=None, enums=[], sets=[], index_length=None, length=None, data_length=None, max_data_length=None, num_rows=None, val_min=None, val_max=None, std_dev=0.4999), Column(id='39fd0bed-29b1-4e4f-af6b-03f2b28495a9', name='country_id', database_id='a6229b2e-5a3d-4a46-93aa-e9474f492ec1', table_id='913c5c1d-3e46-4393-9e5e-744ab04e0ad2', ord=3, internal_name='country_id', is_null_allowed=False, type=<ColumnType.BIGINT: 'bigint'>, alias=None, description=None, size=None, d=None, mean=9.71, median=9.71, concept=None, unit=None, concept_uri=None, unit_uri=None, enums=[], sets=[], index_length=None, length=None, data_length=None, max_data_length=None, num_rows=None, val_min=None, val_max=None, std_dev=5.5268), Column(id='400924f5-09d5-412c-a789-afa3b5664943', name='occupation_id', database_id='a6229b2e-5a3d-4a46-93aa-e9474f492ec1', table_id='913c5c1d-3e46-4393-9e5e-744ab04e0ad2', ord=4, internal_name='occupation_id', is_null_allowed=False, type=<ColumnType.BIGINT: 'bigint'>, alias=None, description=None, size=None, d=None, mean=3.32, median=3.32, concept=None, unit=None, concept_uri=None, unit_uri=None, enums=[], sets=[], index_length=None, length=None, data_length=None, max_data_length=None, num_rows=None, val_min=None, val_max=None, std_dev=1.2718)], constraints=Constraints(uniques=[], foreign_keys=[], checks=[], primary_key=[PrimaryKey(id='416d6f45-c608-4d0d-9079-eb75d85c8276', table=TableBrief(id='913c5c1d-3e46-4393-9e5e-744ab04e0ad2', database_id='a6229b2e-5a3d-4a46-93aa-e9474f492ec1', name='participants', description='Core participant table containing participant identifier, age, and foreign keys to demographic lookup tables.', internal_name='participants', is_versioned=True, is_public=True, is_schema_public=True, owned_by='gokayyil'), column=ColumnBrief(id='fc7636e8-1850-432b-ad5d-996a338b7ad1', name='participant_id', database_id='a6229b2e-5a3d-4a46-93aa-e9474f492ec1', table_id='913c5c1d-3e46-4393-9e5e-744ab04e0ad2', internal_name='participant_id', type=<ColumnType.BIGINT: 'bigint'>, alias=None))]), internal_name='participants', is_versioned=True, queue_name='dbrepo', routing_key='dbrepo.a6229b2e-5a3d-4a46-93aa-e9474f492ec1.913c5c1d-3e46-4393-9e5e-744ab04e0ad2', is_public=True, is_schema_public=True, identifiers=[], description='Core participant table containing participant identifier, age, and foreign keys to demographic lookup tables.', queue_type='quorum', num_rows=100, data_length=16384, max_data_length=0, avg_row_length=163), Table(id='8a73da1b-c5b1-4666-968c-ac1d47dbcbc7', database_id='a6229b2e-5a3d-4a46-93aa-e9474f492ec1', name='occupations', owner=UserBrief(username='gokayyil', id=None, name=None, orcid=None, qualified_name=None, given_name=None, family_name=None), columns=[Column(id='8392bcb1-8035-46b7-aab1-96f7cfb0f67f', name='occupation_id', database_id='a6229b2e-5a3d-4a46-93aa-e9474f492ec1', table_id='8a73da1b-c5b1-4666-968c-ac1d47dbcbc7', ord=0, internal_name='occupation_id', is_null_allowed=False, type=<ColumnType.BIGINT: 'bigint'>, alias=None, description=None, size=None, d=None, mean=3.0, median=3.0, concept=None, unit=None, concept_uri=None, unit_uri=None, enums=[], sets=[], index_length=None, length=None, data_length=None, max_data_length=None, num_rows=None, val_min=None, val_max=None, std_dev=1.4142), Column(id='a2c4ccf0-5063-44a3-9232-a197611236af', name='occupation_name', database_id='a6229b2e-5a3d-4a46-93aa-e9474f492ec1', table_id='8a73da1b-c5b1-4666-968c-ac1d47dbcbc7', ord=1, internal_name='occupation_name', is_nul

In [3]:
[m for m in dir(client) if "table" in m.lower()]

['analyse_table_statistics',
 'create_table',
 'create_table_data',
 'delete_table',
 'delete_table_data',
 'get_table',
 'get_table_data',
 'get_table_data_count',
 'get_table_history',
 'get_tables',
 'import_table_data',
 'update_table_column',
 'update_table_data',
 'update_table_statistics']

In [5]:
import inspect

print(inspect.signature(client.create_table))

(database_id: str, name: str, is_public: bool, is_schema_public: bool, dataframe: pandas.DataFrame, description: str = None, with_data: bool = True) -> dbrepo.api.dto.TableBrief

In [6]:
import pandas as pd
from pathlib import Path

processed_dir = Path("../data/processed")

table_files = {
    "countries": "countries.csv",
    "genders": "genders.csv",
    "occupations": "occupations.csv",
    "participants": "participants.csv",
    "coffee_consumption": "coffee_consumption.csv",
    "sleep_metrics": "sleep_metrics.csv",
    "health_metrics": "health_metrics.csv",
    "lifestyle_metrics": "lifestyle_metrics.csv"
}

for table_name, filename in table_files.items():
    df_table = pd.read_csv(processed_dir / filename)
    print(table_name, df_table.shape)
    display(df_table.head())

countries (20, 2)

   country_id country_name
0           1    Australia
1           2      Belgium
2           3       Brazil
3           4       Canada
4           5        China

genders (3, 2)

   gender_id gender_name
0          1      Female
1          2        Male
2          3       Other

occupations (5, 2)

   occupation_id occupation_name
0              1      Healthcare
1              2          Office
2              3           Other
3              4         Service
4              5         Student

participants (10000, 5)

   participant_id  age  gender_id  country_id  occupation_id
0               1   40          2           8              3
1               2   33          2           8              4
2               3   42          2           3              2
3               4   53          2           8              3
4               5   32          1          16              5

coffee_consumption (10000, 3)

   participant_id  coffee_intake_cups_per_day  caffeine_mg_per_day
0               1                         3.5                328.1
1               2                         1.0                 94.1
2               3                         5.3                503.7
3               4                         2.6                249.2
4               5                         3.1                298.0

sleep_metrics (10000, 3)

   participant_id  sleep_hours sleep_quality
0               1          7.5          Good
1               2          6.2          Good
2               3          5.9          Fair
3               4          7.3          Good
4               5          5.3          Fair

health_metrics (10000, 4)

   participant_id   bmi  heart_rate_bpm health_issues
0               1  24.9              78           NaN
1               2  20.0              67           NaN
2               3  22.7              59          Mild
3               4  24.7              71          Mild
4               5  24.1              76          Mild

lifestyle_metrics (10000, 5)

,participant_id,stress_level,physical_activity_hours,smoking,alcohol_consumption
0,1,Low,14.5,False,False
1,2,Low,11.0,False,False
2,3,Medium,11.2,False,False
3,4,Low,6.6,False,False
4,5,Medium,8.5,False,True

In [8]:
primary_keys = {
    "countries": "country_id",
    "genders": "gender_id",
    "occupations": "occupation_id",
    "participants": "participant_id",
    "coffee_consumption": "participant_id",
    "sleep_metrics": "participant_id",
    "health_metrics": "participant_id",
    "lifestyle_metrics": "participant_id"
}

created_tables = {}

for table_name, filename in table_files.items():
    df_table = pd.read_csv(processed_dir / filename)

    if table_name == "health_metrics":
        df_table["health_issues"] = df_table["health_issues"].fillna("None")

    pk = primary_keys[table_name]
    df_table = df_table.set_index(pk)

    print(f"Creating table: {table_name} with shape {df_table.shape}, primary key: {pk}")

    created_table = client.create_table(
        database_id=DATABASE_ID,
        name=table_name,
        is_public=True,
        is_schema_public=True,
        dataframe=df_table,
        description=table_descriptions[table_name],
        with_data=True
    )

    created_tables[table_name] = created_table

    print(created_table)

Creating table: countries with shape (20, 1), primary key: country_id
2026-05-26 15:16:03,331 root         WARNING default to 'text' for column country_name and type <class 'numpy.dtype'>

ResponseCodeError: Failed to upload: response code: 500 is not 201 (CREATED) or 204 (NO CONTENT): {"timestamp":"2026-05-26T13:16:44.595+00:00","status":500,"error":"Internal Server Error","path":"/api/v1/upload"}

In [9]:
tables = client.get_tables(DATABASE_ID)

for table in tables:
    print(table.id, table.name)

018641cc-175b-4fff-b05c-b5afe4d9733c countries

In [10]:
created_tables = {
    "countries": client.get_table(
        database_id=DATABASE_ID,
        table_id="018641cc-175b-4fff-b05c-b5afe4d9733c"
    )
}

for table_name, filename in table_files.items():
    if table_name == "countries":
        continue

    df_table = pd.read_csv(processed_dir / filename)

    if table_name == "health_metrics":
        df_table["health_issues"] = df_table["health_issues"].fillna("None")

    pk = primary_keys[table_name]
    df_table = df_table.set_index(pk)

    print(f"Creating schema only table: {table_name}")

    created_table = client.create_table(
        database_id=DATABASE_ID,
        name=table_name,
        is_public=True,
        is_schema_public=True,
        dataframe=df_table,
        description=table_descriptions[table_name],
        with_data=False
    )

    created_tables[table_name] = created_table
    print(created_table.id, created_table.name)

Creating schema only table: genders
2026-05-26 15:18:43,995 root         WARNING default to 'text' for column gender_name and type <class 'numpy.dtype'>
e5980c01-dacf-481a-84f8-1f83bd84095c genders
Creating schema only table: occupations
2026-05-26 15:18:44,406 root         WARNING default to 'text' for column occupation_name and type <class 'numpy.dtype'>
8a73da1b-c5b1-4666-968c-ac1d47dbcbc7 occupations
Creating schema only table: participants
913c5c1d-3e46-4393-9e5e-744ab04e0ad2 participants
Creating schema only table: coffee_consumption
6e828acb-4698-4f34-9a62-1a753b768554 coffee_consumption
Creating schema only table: sleep_metrics
2026-05-26 15:18:45,625 root         WARNING default to 'text' for column sleep_quality and type <class 'numpy.dtype'>
83a691e2-a7ad-4b5a-b468-03c3d63d727b sleep_metrics
Creating schema only table: health_metrics
2026-05-26 15:18:45,972 root         WARNING default to 'text' for column health_issues and type <class 'numpy.dtype'>
9abc69b3-932e-4a20-93a6-9e3cb4ac9676 health_metrics
Creating schema only table: lifestyle_metrics
2026-05-26 15:18:46,361 root         WARNING default to 'text' for column stress_level and type <class 'numpy.dtype'>
dddb6b09-ba3f-4003-bf93-73786410e886 lifestyle_metrics

In [11]:
countries_df = pd.read_csv(processed_dir / "countries.csv")

countries_table_id = "018641cc-175b-4fff-b05c-b5afe4d9733c"

client.import_table_data(
    database_id=DATABASE_ID,
    table_id=countries_table_id,
    dataframe=countries_df
)

print("countries import requested")

ResponseCodeError: Failed to upload: response code: 500 is not 201 (CREATED) or 204 (NO CONTENT): {"timestamp":"2026-05-26T13:20:48.607+00:00","status":500,"error":"Internal Server Error","path":"/api/v1/upload"}

In [12]:
import inspect
print(inspect.signature(client.create_table_data))

(database_id: str, table_id: str, data: dict) -> None

In [13]:
countries_df = pd.read_csv(processed_dir / "countries.csv")

first_row = countries_df.iloc[0].to_dict()
print(first_row)

client.create_table_data(
    database_id=DATABASE_ID,
    table_id="018641cc-175b-4fff-b05c-b5afe4d9733c",
    data=first_row
)

print("Inserted first country row")

{'country_id': 1, 'country_name': 'Australia'}
Inserted first country row

In [14]:
countries_df = pd.read_csv(processed_dir / "countries.csv")

for _, row in countries_df.iloc[1:].iterrows():
    client.create_table_data(
        database_id=DATABASE_ID,
        table_id="018641cc-175b-4fff-b05c-b5afe4d9733c",
        data=row.to_dict()
    )

print("Inserted remaining countries")

Inserted remaining countries

In [15]:
count = client.get_table_data_count(
    database_id=DATABASE_ID,
    table_id="018641cc-175b-4fff-b05c-b5afe4d9733c"
)

print(count)

20

In [16]:
table_ids = {
    "countries": "018641cc-175b-4fff-b05c-b5afe4d9733c",
    "genders": "e5980c01-dacf-481a-84f8-1f83bd84095c",
    "occupations": "8a73da1b-c5b1-4666-968c-ac1d47dbcbc7"
}

for table_name in ["genders", "occupations"]:

    df = pd.read_csv(processed_dir / f"{table_name}.csv")

    for _, row in df.iterrows():
        client.create_table_data(
            database_id=DATABASE_ID,
            table_id=table_ids[table_name],
            data=row.to_dict()
        )

    count = client.get_table_data_count(
        database_id=DATABASE_ID,
        table_id=table_ids[table_name]
    )

    print(table_name, count)

genders 3
occupations 5

In [29]:
INTEGER_COLUMNS = {
    "country_id",
    "gender_id",
    "occupation_id",
    "participant_id",
    "age",
    "heart_rate_bpm"
}

DECIMAL_COLUMNS = {
    "coffee_intake_cups_per_day",
    "caffeine_mg_per_day",
    "sleep_hours",
    "bmi",
    "physical_activity_hours"
}

BOOLEAN_COLUMNS = {
    "smoking",
    "alcohol_consumption"
}


def clean_value_by_column(column, value):
    if pd.isna(value):
        return None

    if column in INTEGER_COLUMNS:
        return int(value)

    if column in DECIMAL_COLUMNS:
        return str(float(value))

    if column in BOOLEAN_COLUMNS:
        return bool(value)

    return str(value)


def row_to_clean_dict(row):
    return {
        column: clean_value_by_column(column, value)
        for column, value in row.to_dict().items()
    }


def insert_dataframe_rows(database_id, table_id, dataframe, table_name):
    total_rows = len(dataframe)

    for index, (_, row) in enumerate(dataframe.iterrows(), start=1):
        data = row_to_clean_dict(row)

        client.create_table_data(
            database_id=database_id,
            table_id=table_id,
            data=data
        )

        if index % 100 == 0 or index == total_rows:
            print(f"{table_name}: inserted {index}/{total_rows} rows")

    print(f"{table_name}: completed")

In [18]:
participants_sample = pd.read_csv(
    processed_dir / "participants.csv"
).head(100)

insert_dataframe_rows(
    DATABASE_ID,
    "913c5c1d-3e46-4393-9e5e-744ab04e0ad2",
    participants_sample,
    "participants_sample"
)

participants_sample: inserted 100/100 rows
participants_sample: completed

In [19]:
client.get_table_data_count(
    DATABASE_ID,
    "913c5c1d-3e46-4393-9e5e-744ab04e0ad2"
)

100

In [20]:
table_ids.update({
    "participants": "913c5c1d-3e46-4393-9e5e-744ab04e0ad2",
    "coffee_consumption": "6e828acb-4698-4f34-9a62-1a753b768554",
    "sleep_metrics": "83a691e2-a7ad-4b5a-b468-03c3d63d727b",
    "health_metrics": "9abc69b3-932e-4a20-93a6-9e3cb4ac9676",
    "lifestyle_metrics": "dddb6b09-ba3f-4003-bf93-73786410e886"
})

for table_name in [
    "coffee_consumption",
    "sleep_metrics",
    "health_metrics",
    "lifestyle_metrics"
]:
    df = pd.read_csv(processed_dir / f"{table_name}.csv").head(100)

    if table_name == "health_metrics":
        df["health_issues"] = df["health_issues"].fillna("None")

    insert_dataframe_rows(
        DATABASE_ID,
        table_ids[table_name],
        df,
        table_name
    )

    count = client.get_table_data_count(
        DATABASE_ID,
        table_ids[table_name]
    )

    print(table_name, count)

ResponseCodeError: Failed to insert table data: response code: 500 is not 201 (CREATED): {"timestamp":"2026-05-26T13:27:20.096+00:00","status":500,"error":"Internal Server Error","path":"/api/v1/database/a6229b2e-5a3d-4a46-93aa-e9474f492ec1/table/6e828acb-4698-4f34-9a62-1a753b768554/data"}

In [22]:
coffee_df = pd.read_csv(processed_dir / "coffee_consumption.csv").head(1)

print(row_to_clean_dict(coffee_df.iloc[0]))

client.create_table_data(
    database_id=DATABASE_ID,
    table_id=table_ids["coffee_consumption"],
    data=row_to_clean_dict(coffee_df.iloc[0])
)

print("Inserted first coffee row")

{'participant_id': 1.0, 'coffee_intake_cups_per_day': 3.5, 'caffeine_mg_per_day': 328.1}

ResponseCodeError: Failed to insert table data: response code: 500 is not 201 (CREATED): {"timestamp":"2026-05-26T13:29:24.465+00:00","status":500,"error":"Internal Server Error","path":"/api/v1/database/a6229b2e-5a3d-4a46-93aa-e9474f492ec1/table/6e828acb-4698-4f34-9a62-1a753b768554/data"}

In [23]:
coffee_table = client.get_table(
    database_id=DATABASE_ID,
    table_id=table_ids["coffee_consumption"]
)

print(coffee_table)

id='6e828acb-4698-4f34-9a62-1a753b768554' database_id='a6229b2e-5a3d-4a46-93aa-e9474f492ec1' name='coffee_consumption' owner=UserBrief(username='gokayyil', id=None, name=None, orcid=None, qualified_name=None, given_name=None, family_name=None) columns=[Column(id='ea78c4ce-44da-4468-b4d7-3880baf9b1e1', name='participant_id', database_id='a6229b2e-5a3d-4a46-93aa-e9474f492ec1', table_id='6e828acb-4698-4f34-9a62-1a753b768554', ord=0, internal_name='participant_id', is_null_allowed=False, type=<ColumnType.BIGINT: 'bigint'>, alias=None, description=None, size=None, d=None, mean=None, median=None, concept=None, unit=None, concept_uri=None, unit_uri=None, enums=[], sets=[], index_length=None, length=None, data_length=None, max_data_length=None, num_rows=None, val_min=None, val_max=None, std_dev=None), Column(id='d3cf2175-5393-43d6-8707-31a39be698b4', name='coffee_intake_cups_per_day', database_id='a6229b2e-5a3d-4a46-93aa-e9474f492ec1', table_id='6e828acb-4698-4f34-9a62-1a753b768554', ord=1, internal_name='coffee_intake_cups_per_day', is_null_allowed=False, type=<ColumnType.DECIMAL: 'decimal'>, alias=None, description=None, size=40, d=20, mean=None, median=None, concept=None, unit=None, concept_uri=None, unit_uri=None, enums=[], sets=[], index_length=None, length=None, data_length=None, max_data_length=None, num_rows=None, val_min=None, val_max=None, std_dev=None), Column(id='f5f80e8f-af51-4961-bf4d-7ff65264aa6b', name='caffeine_mg_per_day', database_id='a6229b2e-5a3d-4a46-93aa-e9474f492ec1', table_id='6e828acb-4698-4f34-9a62-1a753b768554', ord=2, internal_name='caffeine_mg_per_day', is_null_allowed=False, type=<ColumnType.DECIMAL: 'decimal'>, alias=None, description=None, size=40, d=20, mean=None, median=None, concept=None, unit=None, concept_uri=None, unit_uri=None, enums=[], sets=[], index_length=None, length=None, data_length=None, max_data_length=None, num_rows=None, val_min=None, val_max=None, std_dev=None)] constraints=Constraints(uniques=[], foreign_keys=[], checks=[], primary_key=[PrimaryKey(id='a5cc08a3-7f36-4a92-8ec5-91fd99a92191', table=TableBrief(id='6e828acb-4698-4f34-9a62-1a753b768554', database_id='a6229b2e-5a3d-4a46-93aa-e9474f492ec1', name='coffee_consumption', description='Table containing daily coffee intake in cups and daily caffeine intake in milligrams.', internal_name='coffee_consumption', is_versioned=True, is_public=True, is_schema_public=True, owned_by='gokayyil'), column=ColumnBrief(id='ea78c4ce-44da-4468-b4d7-3880baf9b1e1', name='participant_id', database_id='a6229b2e-5a3d-4a46-93aa-e9474f492ec1', table_id='6e828acb-4698-4f34-9a62-1a753b768554', internal_name='participant_id', type=<ColumnType.BIGINT: 'bigint'>, alias=None))]) internal_name='coffee_consumption' is_versioned=True queue_name='dbrepo' routing_key='dbrepo.a6229b2e-5a3d-4a46-93aa-e9474f492ec1.6e828acb-4698-4f34-9a62-1a753b768554' is_public=True is_schema_public=True identifiers=[] description='Table containing daily coffee intake in cups and daily caffeine intake in milligrams.' queue_type='quorum' num_rows=0 data_length=0 max_data_length=None avg_row_length=None

In [24]:
for column in coffee_table.columns:
    print(column)

id='ea78c4ce-44da-4468-b4d7-3880baf9b1e1' name='participant_id' database_id='a6229b2e-5a3d-4a46-93aa-e9474f492ec1' table_id='6e828acb-4698-4f34-9a62-1a753b768554' ord=0 internal_name='participant_id' is_null_allowed=False type=<ColumnType.BIGINT: 'bigint'> alias=None description=None size=None d=None mean=None median=None concept=None unit=None concept_uri=None unit_uri=None enums=[] sets=[] index_length=None length=None data_length=None max_data_length=None num_rows=None val_min=None val_max=None std_dev=None
id='d3cf2175-5393-43d6-8707-31a39be698b4' name='coffee_intake_cups_per_day' database_id='a6229b2e-5a3d-4a46-93aa-e9474f492ec1' table_id='6e828acb-4698-4f34-9a62-1a753b768554' ord=1 internal_name='coffee_intake_cups_per_day' is_null_allowed=False type=<ColumnType.DECIMAL: 'decimal'> alias=None description=None size=40 d=20 mean=None median=None concept=None unit=None concept_uri=None unit_uri=None enums=[] sets=[] index_length=None length=None data_length=None max_data_length=None num_rows=None val_min=None val_max=None std_dev=None
id='f5f80e8f-af51-4961-bf4d-7ff65264aa6b' name='caffeine_mg_per_day' database_id='a6229b2e-5a3d-4a46-93aa-e9474f492ec1' table_id='6e828acb-4698-4f34-9a62-1a753b768554' ord=2 internal_name='caffeine_mg_per_day' is_null_allowed=False type=<ColumnType.DECIMAL: 'decimal'> alias=None description=None size=40 d=20 mean=None median=None concept=None unit=None concept_uri=None unit_uri=None enums=[] sets=[] index_length=None length=None data_length=None max_data_length=None num_rows=None val_min=None val_max=None std_dev=None

In [25]:
coffee_row = {
    "participant_id": 1,
    "coffee_intake_cups_per_day": "3.5",
    "caffeine_mg_per_day": "328.1"
}

client.create_table_data(
    database_id=DATABASE_ID,
    table_id=table_ids["coffee_consumption"],
    data=coffee_row
)

print("Inserted coffee row with decimals as strings")

Inserted coffee row with decimals as strings

In [28]:
coffee_df = pd.read_csv(processed_dir / "coffee_consumption.csv").iloc[1:100]

insert_dataframe_rows(
    DATABASE_ID,
    table_ids["coffee_consumption"],
    coffee_df,
    "coffee_consumption"
)

count = client.get_table_data_count(
    DATABASE_ID,
    table_ids["coffee_consumption"]
)

print(count)

ResponseCodeError: Failed to insert table data: response code: 500 is not 201 (CREATED): {"timestamp":"2026-05-26T13:32:48.683+00:00","status":500,"error":"Internal Server Error","path":"/api/v1/database/a6229b2e-5a3d-4a46-93aa-e9474f492ec1/table/6e828acb-4698-4f34-9a62-1a753b768554/data"}

In [30]:
coffee_df = pd.read_csv(processed_dir / "coffee_consumption.csv")

test_row = coffee_df.iloc[1]

print(row_to_clean_dict(test_row))

{'participant_id': 2, 'coffee_intake_cups_per_day': '1.0', 'caffeine_mg_per_day': '94.1'}

In [31]:
client.create_table_data(
    database_id=DATABASE_ID,
    table_id=table_ids["coffee_consumption"],
    data={
        "participant_id": 2,
        "coffee_intake_cups_per_day": "1.0",
        "caffeine_mg_per_day": "94.1"
    }
)

print("Inserted coffee row 2 manually")

Inserted coffee row 2 manually

In [32]:
client.get_table_data_count(DATABASE_ID, table_ids["coffee_consumption"])

2

In [33]:
coffee_df = pd.read_csv(
    processed_dir / "coffee_consumption.csv"
).iloc[2:100]

insert_dataframe_rows(
    DATABASE_ID,
    table_ids["coffee_consumption"],
    coffee_df,
    "coffee_consumption"
)

count = client.get_table_data_count(
    DATABASE_ID,
    table_ids["coffee_consumption"]
)

print(count)

coffee_consumption: inserted 98/98 rows
coffee_consumption: completed
100

In [34]:
for table_name in [
    "sleep_metrics",
    "health_metrics",
    "lifestyle_metrics"
]:
    df = pd.read_csv(processed_dir / f"{table_name}.csv").head(100)

    if table_name == "health_metrics":
        df["health_issues"] = df["health_issues"].fillna("None")

    insert_dataframe_rows(
        DATABASE_ID,
        table_ids[table_name],
        df,
        table_name
    )

    count = client.get_table_data_count(
        DATABASE_ID,
        table_ids[table_name]
    )

    print(table_name, count)

sleep_metrics: inserted 100/100 rows
sleep_metrics: completed
sleep_metrics 100
health_metrics: inserted 100/100 rows
health_metrics: completed
health_metrics 100
lifestyle_metrics: inserted 100/100 rows
lifestyle_metrics: completed
lifestyle_metrics 100

In [35]:
[m for m in dir(client) if "view" in m.lower()]

['create_view',
 'delete_view',
 'get_view',
 'get_view_data',
 'get_view_data_count',
 'get_views',
 'update_view']

In [36]:
[m for m in dir(client) if "create" in m.lower()]

['create_container',
 'create_database',
 'create_database_access',
 'create_identifier',
 'create_subset',
 'create_table',
 'create_table_data',
 'create_view']

In [37]:
import inspect

for method_name in dir(client):
    if "view" in method_name.lower():
        print(method_name)

create_view
delete_view
get_view
get_view_data
get_view_data_count
get_views
update_view

In [38]:
import inspect
print(inspect.signature(client.create_view))

(database_id: str, name: str, query: dbrepo.api.dto.QueryDefinition, is_public: bool, is_schema_public: bool) -> dbrepo.api.dto.ViewBrief

In [39]:
from dbrepo.api.dto import QueryDefinition

help(QueryDefinition)

Help on class QueryDefinition in module dbrepo.api.dto:

class QueryDefinition(pydantic.main.BaseModel)
 |  QueryDefinition(**data: 'Any') -> 'None'
 |
 |  Method resolution order:
 |      QueryDefinition
 |      pydantic.main.BaseModel
 |      builtins.object
 |
 |  Data descriptors defined here:
 |
 |  __weakref__
 |      list of weak references to the object
 |
 |  ----------------------------------------------------------------------
 |  Data and other attributes defined here:
 |
 |  __abstractmethods__ = frozenset()
 |
 |  __annotations__ = {'columns': 'List[str]', 'datasources': 'List[str]',...
 |
 |  __class_vars__ = set()
 |
 |  __private_attributes__ = {}
 |
 |  __pydantic_complete__ = True
 |
 |  __pydantic_computed_fields__ = {}
 |
 |  __pydantic_core_schema__ = {'cls': <class 'dbrepo.api.dto.QueryDefinit...
 |
 |  __pydantic_custom_init__ = False
 |
 |  __pydantic_decorators__ = DecoratorInfos(validators={}, field_validato...
 |
 |  __pydantic_extra_info__ = None
 |
 |  __pydantic_fields__ = {'columns': FieldInfo(annotation=List[str], requ...
 |
 |  __pydantic_generic_metadata__ = {'args': (), 'origin': None, 'paramete...
 |
 |  __pydantic_parent_namespace__ = None
 |
 |  __pydantic_post_init__ = None
 |
 |  __pydantic_serializer__ = SchemaSerializer(serializer=PolymorphismTram...
 |
 |  __pydantic_setattr_handlers__ = {}
 |
 |  __pydantic_validator__ = SchemaValidator(title="QueryDefinition", vali...
 |
 |  model_config = {}
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from pydantic.main.BaseModel:
 |
 |  __copy__(self) -> 'Self'
 |      Returns a shallow copy of the model.
 |
 |  __deepcopy__(self, memo: 'dict[int, Any] | None' = None) -> 'Self'
 |      Returns a deep copy of the model.
 |
 |  __delattr__(self, item: 'str') -> 'Any'
 |      Implement delattr(self, name).
 |
 |  __eq__(self, other: 'Any') -> 'bool'
 |      Return self==value.
 |
 |  __getattr__(self, item: 'str') -> 'Any'
 |
 |  __getstate__(self) -> 'dict[Any, Any]'
 |      Helper for pickle.
 |
 |  __init__(self, /, **data: 'Any') -> 'None'
 |      Create a new model by parsing and validating input data from keyword arguments.
 |
 |      Raises [`ValidationError`][pydantic_core.ValidationError] if the input data cannot be
 |      validated to form a valid model.
 |
 |      `self` is explicitly positional-only to allow `self` as a field name.
 |
 |  __iter__(self) -> 'TupleGenerator'
 |      So `dict(model)` works.
 |
 |  __pretty__(self, fmt: 'Callable[[Any], Any]', **kwargs: 'Any') -> 'Generator[Any]' from pydantic._internal._repr.Representation
 |      Used by devtools (https://python-devtools.helpmanual.io/) to pretty print objects.
 |
 |  __replace__(self, **changes: 'Any') -> 'Self'
 |      # Because we make use of `@dataclass_transform()`, `__replace__` is already synthesized by
 |      # type checkers, so we define the implementation in this `if not TYPE_CHECKING:` block:
 |
 |  __repr__(self) -> 'str'
 |      Return repr(self).
 |
 |  __repr_args__(self) -> '_repr.ReprArgs'
 |
 |  __repr_name__(self) -> 'str' from pydantic._internal._repr.Representation
 |      Name of the instance's class, used in __repr__.
 |
 |  __repr_recursion__(self, object: 'Any') -> 'str' from pydantic._internal._repr.Representation
 |      Returns the string representation of a recursive object.
 |
 |  __repr_str__(self, join_str: 'str') -> 'str' from pydantic._internal._repr.Representation
 |
 |  __rich_repr__(self) -> 'RichReprResult' from pydantic._internal._repr.Representation
 |      Used by Rich (https://rich.readthedocs.io/en/stable/pretty.html) to pretty print objects.
 |
 |  __setattr__(self, name: 'str', value: 'Any') -> 'None'
 |      Implement setattr(self, name, value).
 |
 |  __setstate__(self, state: 'dict[Any, Any]') -> 'None'
 |
 |  __str__(self) -> 'str'
 |      Return str(self).
 |
 |  copy(
 |      self,
 |      *,
 |      include: 'AbstractSetIntStr | MappingIntStrAny | None' = None,
 |      exclude: 'AbstractSetIntStr | MappingIntStrAny | None' = None,
 |      update: 'Dict[str, Any] | None' = None,
 |      deep: 'bool' = False
 |  ) -> 'Self'
 |      Returns a copy of the model.
 |
 |      !!! warning "Deprecated"
 |          This method is now deprecated; use `model_copy` instead.
 |
 |      If you need `include` or `exclude`, use:
 |
 |      ```python {test="skip" lint="skip"}
 |      data = self.model_dump(include=include, exclude=exclude, round_trip=True)
 |      data = {**data, **(update or {})}
 |      copied = self.model_validate(data)
 |      ```
 |
 |      Args:
 |          include: Optional set or mapping specifying which fields to include in the copied model.
 |          exclude: Optional set or mapping specifying which fields to exclude in the copied model.
 |          update: Optional dictionary of field-value pairs to override field values in the copied model.
 |          deep: If True, the values of fields that are Pydantic models will be deep-copied.
 |
 |      Returns:
 |          A copy of the model with included, excluded and updated fields as specified.
 |
 |  dict(
 |      self,
 |      *,
 |      include: 'IncEx | None' = None,
 |      exclude: 'IncEx | None' = None,
 |      by_alias: 'bool' = False,
 |      exclude_unset: 'bool' = False,
 |      exclude_defaults: 'bool' = False,
 |      exclude_none: 'bool' = False
 |  ) -> 'Dict[str, Any]'
 |
 |  json(
 |      self,
 |      *,
 |      include: 'IncEx | None' = None,
 |      exclude: 'IncEx | None' = None,
 |      by_alias: 'bool' = False,
 |      exclude_unset: 'bool' = False,
 |      exclude_defaults: 'bool' = False,
 |      exclude_none: 'bool' = False,
 |      encoder: 'Callable[[Any], Any] | None' = PydanticUndefined,
 |      models_as_dict: 'bool' = PydanticUndefined,
 |      **dumps_kwargs: 'Any'
 |  ) -> 'str'
 |
 |  model_copy(
 |      self,
 |      *,
 |      update: 'Mapping[str, Any] | None' = None,
 |      deep: 'bool' = False
 |  ) -> 'Self'
 |      !!! abstract "Usage Documentation"
 |          [`model_copy`](../concepts/models.md#model-copy)
 |
 |      Returns a copy of the model.
 |
 |      !!! note
 |          The underlying instance's [`__dict__`][object.__dict__] attribute is copied. This
 |          might have unexpected side effects if you store anything in it, on top of the model
 |          fields (e.g. the value of [cached properties][functools.cached_property]).
 |
 |      Args:
 |          update: Values to change/add in the new model. Note: the data is not validated
 |              before creating the new model. You should trust this data.
 |          deep: Set to `True` to make a deep copy of the model.
 |
 |      Returns:
 |          New model instance.
 |
 |  model_dump(
 |      self,
 |      *,
 |      mode: "Literal['json', 'python'] | str" = 'python',
 |      include: 'IncEx | None' = None,
 |      exclude: 'IncEx | None' = None,
 |      context: 'Any | None' = None,
 |      by_alias: 'bool | None' = None,
 |      exclude_unset: 'bool' = False,
 |      exclude_defaults: 'bool' = False,
 |      exclude_none: 'bool' = False,
 |      exclude_computed_fields: 'bool' = False,
 |      round_trip: 'bool' = False,
 |      warnings: "bool | Literal['none', 'warn', 'error']" = True,
 |      fallback: 'Callable[[Any], Any] | None' = None,
 |      serialize_as_any: 'bool' = False,
 |      polymorphic_serialization: 'bool | None' = None
 |  ) -> 'dict[str, Any]'
 |      !!! abstract "Usage Documentation"
 |          [`model_dump`](../concepts/serialization.md#python-mode)
 |
 |      Generate a dictionary representation of the model, optionally specifying which fields to include or exclude.
 |
 |      Args:
 |          mode: The mode in which `to_python` should run.
 |              If mode is 'json', the output will only contain JSON serializable types.
 |              If mode is 'python', the output may contain non-JSON-serializable Python objects.
 |          include: A set of fields to include in the output.
 |          exclude: A set of fields to exclude from the output.
 |          context: Additional context to pass to the serializer.
 |          by_alias: Whether to use the field's alias in the dictionary key if defined.
 |          exclude_unset: Whether to exclude fields that have not been explicitly set.
 |          exclude_defaults: Whether to exclude fields that are set to their default value.
 |          exclude_none: Whether to exclude fields that have a value of `None`.
 |          exclude_computed_fields: Whether to exclude computed fields.
 |              While this can be useful for round-tripping, it is usually recommended to use the dedicated
 |              `round_trip` parameter instead.
 |          round_trip: If True, dumped values should be valid as input for non-idempotent types such as Json[T].
 |          warnings: How to handle serialization errors. False/"none" ignores them, True/"warn" logs errors,
 |              "error" raises a [`PydanticSerializationError`][pydantic_core.PydanticSerializationError].
 |          fallback: A function to call when an unknown value is encountered. If not provided,
 |              a [`PydanticSerializationError`][pydantic_core.PydanticSerializationError] error is raised.
 |          serialize_as_any: Whether to serialize fields with duck-typing serialization behavior.
 |          polymorphic_serialization: Whether to use model and dataclass polymorphic serialization for this call.
 |
 |      Returns:
 |          A dictionary representation of the model.
 |
 |  model_dump_json(
 |      self,
 |      *,
 |      indent: 'int | None' = None,
 |      ensure_ascii: 'bool' = False,
 |      include: 'IncEx | None' = None,
 |      exclude: 'IncEx | None' = None,
 |      context: 'Any | None' = None,
 |      by_alias: 'bool | None' = None,
 |      exclude_unset: 'bool' = False,
 |      exclude_defaults: 'bool' = False,
 |      exclude_none: 'bool' = False,
 |      exclude_computed_fields: 'bool' = False,
 |      round_trip: 'bool' = False,
 |      warnings: "bool | Literal['none', 'warn', 'error']" = True,
 |      fallback: 'Callable[[Any], Any] | None' = None,
 |      serialize_as_any: 'bool' = False,
 |      polymorphic_serialization: 'bool | None' = None
 |  ) -> 'str'
 |      !!! abstract "Usage Documentation"
 |          [`model_dump_json`](../concepts/serialization.md#json-mode)
 |
 |      Generates a JSON representation of the model using Pydantic's `to_json` method.
 |
 |      Args:
 |          indent: Indentation to use in the JSON output. If None is passed, the output will be compact.
 |          ensure_ascii: If `True`, the output is guaranteed to have all incoming non-ASCII characters escaped.
 |              If `False` (the default), these characters will be output as-is.
 |          include: Field(s) to include in the JSON output.
 |          exclude: Field(s) to exclude from the JSON output.
 |          context: Additional context to pass to the serializer.
 |          by_alias: Whether to serialize using field aliases.
 |          exclude_unset: Whether to exclude fields that have not been explicitly set.
 |          exclude_defaults: Whether to exclude fields that are set to their default value.
 |          exclude_none: Whether to exclude fields that have a value of `None`.
 |          exclude_computed_fields: Whether to exclude computed fields.
 |              While this can be useful for round-tripping, it is usually recommended to use the dedicated
 |              `round_trip` parameter instead.
 |          round_trip: If True, dumped values should be valid as input for non-idempotent types such as Json[T].
 |          warnings: How to handle serialization errors. False/"none" ignores them, True/"warn" logs errors,
 |              "error" raises a [`PydanticSerializationError`][pydantic_core.PydanticSerializationError].
 |          fallback: A function to call when an unknown value is encountered. If not provided,
 |              a [`PydanticSerializationError`][pydantic_core.PydanticSerializationError] error is raised.
 |          serialize_as_any: Whether to serialize fields with duck-typing serialization behavior.
 |          polymorphic_serialization: Whether to use model and dataclass polymorphic serialization for this call.
 |
 |      Returns:
 |          A JSON string representation of the model.
 |
 |  model_post_init(self, context: 'Any', /) -> 'None'
 |      Override this method to perform additional initialization after `__init__` and `model_construct`.
 |      This is useful if you want to do some validation that requires the entire model to be initialized.
 |
 |  ----------------------------------------------------------------------
 |  Class methods inherited from pydantic.main.BaseModel:
 |
 |  __class_getitem__(typevar_values: 'type[Any] | tuple[type[Any], ...]') -> 'type[BaseModel] | _forward_ref.PydanticRecursiveRef'
 |
 |  __get_pydantic_core_schema__(
 |      source: 'type[BaseModel]',
 |      handler: 'GetCoreSchemaHandler',
 |      /
 |  ) -> 'CoreSchema'
 |
 |  __get_pydantic_json_schema__(
 |      core_schema: 'CoreSchema',
 |      handler: 'GetJsonSchemaHandler',
 |      /
 |  ) -> 'JsonSchemaValue'
 |      Hook into generating the model's JSON schema.
 |
 |      Args:
 |          core_schema: A `pydantic-core` CoreSchema.
 |              You can ignore this argument and call the handler with a new CoreSchema,
 |              wrap this CoreSchema (`{'type': 'nullable', 'schema': current_schema}`),
 |              or just call the handler with the original schema.
 |          handler: Call into Pydantic's internal JSON schema generation.
 |              This will raise a `pydantic.errors.PydanticInvalidForJsonSchema` if JSON schema
 |              generation fails.
 |              Since this gets called by `BaseModel.model_json_schema` you can override the
 |              `schema_generator` argument to that function to change JSON schema generation globally
 |              for a type.
 |
 |      Returns:
 |          A JSON schema, as a Python object.
 |
 |  __pydantic_init_subclass__(**kwargs: 'Any') -> 'None'
 |      This is intended to behave just like `__init_subclass__`, but is called by `ModelMetaclass`
 |      only after basic class initialization is complete. In particular, attributes like `model_fields` will
 |      be present when this is called, but forward annotations are not guaranteed to be resolved yet,
 |      meaning that creating an instance of the class may fail.
 |
 |      This is necessary because `__init_subclass__` will always be called by `type.__new__`,
 |      and it would require a prohibitively large refactor to the `ModelMetaclass` to ensure that
 |      `type.__new__` was called in such a manner that the class would already be sufficiently initialized.
 |
 |      This will receive the same `kwargs` that would be passed to the standard `__init_subclass__`, namely,
 |      any kwargs passed to the class definition that aren't used internally by Pydantic.
 |
 |      Args:
 |          **kwargs: Any keyword arguments passed to the class definition that aren't used internally
 |              by Pydantic.
 |
 |      Note:
 |          You may want to override [`__pydantic_on_complete__()`][pydantic.main.BaseModel.__pydantic_on_complete__]
 |          instead, which is called once the class and its fields are fully initialized and ready for validation.
 |
 |  __pydantic_on_complete__() -> 'None'
 |      This is called once the class and its fields are fully initialized and ready to be used.
 |
 |      This typically happens when the class is created (just before
 |      [`__pydantic_init_subclass__()`][pydantic.main.BaseModel.__pydantic_init_subclass__] is called on the superclass),
 |      except when forward annotations are used that could not immediately be resolved.
 |      In that case, it will be called later, when the model is rebuilt automatically or explicitly using
 |      [`model_rebuild()`][pydantic.main.BaseModel.model_rebuild].
 |
 |  construct(_fields_set: 'set[str] | None' = None, **values: 'Any') -> 'Self'
 |
 |  from_orm(obj: 'Any') -> 'Self'
 |
 |  model_construct(_fields_set: 'set[str] | None' = None, **values: 'Any') -> 'Self'
 |      Creates a new instance of the `Model` class with validated data.
 |
 |      Creates a new model setting `__dict__` and `__pydantic_fields_set__` from trusted or pre-validated data.
 |      Default values are respected, but no other validation is performed.
 |
 |      !!! note
 |          `model_construct()` generally respects the `model_config.extra` setting on the provided model.
 |          That is, if `model_config.extra == 'allow'`, then all extra passed values are added to the model instance's `__dict__`
 |          and `__pydantic_extra__` fields. If `model_config.extra == 'ignore'` (the default), then all extra passed values are ignored.
 |          Because no validation is performed with a call to `model_construct()`, having `model_config.extra == 'forbid'` does not result in
 |          an error if extra values are passed, but they will be ignored.
 |
 |      Args:
 |          _fields_set: A set of field names that were originally explicitly set during instantiation. If provided,
 |              this is directly used for the [`model_fields_set`][pydantic.BaseModel.model_fields_set] attribute.
 |              Otherwise, the field names from the `values` argument will be used.
 |          values: Trusted or pre-validated data dictionary.
 |
 |      Returns:
 |          A new instance of the `Model` class with validated data.
 |
 |  model_json_schema(
 |      by_alias: 'bool' = True,
 |      ref_template: 'str' = '#/$defs/{model}',
 |      schema_generator: 'type[GenerateJsonSchema]' = <class 'pydantic.json_schema.GenerateJsonSchema'>,
 |      mode: 'JsonSchemaMode' = 'validation',
 |      *,
 |      union_format: "Literal['any_of', 'primitive_type_array']" = 'any_of'
 |  ) -> 'dict[str, Any]'
 |      Generates a JSON schema for a model class.
 |
 |      Args:
 |          by_alias: Whether to use attribute aliases or not.
 |          ref_template: The reference template.
 |          union_format: The format to use when combining schemas from unions together. Can be one of:
 |
 |              - `'any_of'`: Use the [`anyOf`](https://json-schema.org/understanding-json-schema/reference/combining#anyOf)
 |              keyword to combine schemas (the default).
 |              - `'primitive_type_array'`: Use the [`type`](https://json-schema.org/understanding-json-schema/reference/type)
 |              keyword as an array of strings, containing each type of the combination. If any of the schemas is not a primitive
 |              type (`string`, `boolean`, `null`, `integer` or `number`) or contains constraints/metadata, falls back to
 |              `any_of`.
 |          schema_generator: To override the logic used to generate the JSON schema, as a subclass of
 |              `GenerateJsonSchema` with your desired modifications
 |          mode: The mode in which to generate the schema.
 |
 |      Returns:
 |          The JSON schema for the given model class.
 |
 |  model_parametrized_name(params: 'tuple[type[Any], ...]') -> 'str'
 |      Compute the class name for parametrizations of generic classes.
 |
 |      This method can be overridden to achieve a custom naming scheme for generic BaseModels.
 |
 |      Args:
 |          params: Tuple of types of the class. Given a generic class
 |              `Model` with 2 type variables and a concrete model `Model[str, int]`,
 |              the value `(str, int)` would be passed to `params`.
 |
 |      Returns:
 |          String representing the new class where `params` are passed to `cls` as type variables.
 |
 |      Raises:
 |          TypeError: Raised when trying to generate concrete names for non-generic models.
 |
 |  model_rebuild(
 |      *,
 |      force: 'bool' = False,
 |      raise_errors: 'bool' = True,
 |      _parent_namespace_depth: 'int' = 2,

In [40]:
import inspect
print(inspect.signature(QueryDefinition))

(*, columns: List[str], datasources: List[str], joins: Optional[List[dbrepo.api.dto.JoinDefinition]] = None, filters: Optional[List[dbrepo.api.dto.FilterDefinition]] = None, orders: Optional[List[dbrepo.api.dto.OrderDefinition]] = None) -> None

In [41]:
from dbrepo.api.dto import JoinDefinition
import inspect

print(inspect.signature(JoinDefinition))
print(JoinDefinition.model_fields)

(**data: 'Any') -> 'None'
{'type': FieldInfo(annotation=ForwardRef('JoinType'), required=True), 'datasource': FieldInfo(annotation=str, required=True), 'conditionals': FieldInfo(annotation=ForwardRef('List[ConditionalDefinition]'), required=True)}

In [42]:
from dbrepo.api.dto import ConditionalDefinition
import inspect

print(inspect.signature(ConditionalDefinition))
print(ConditionalDefinition.model_fields)

(*, column: str, foreign_column: str) -> None
{'column': FieldInfo(annotation=str, required=True), 'foreign_column': FieldInfo(annotation=str, required=True)}

In [43]:
from dbrepo.api.dto import JoinType

print(list(JoinType))

[<JoinType.INNER: 'inner'>, <JoinType.LEFT: 'left'>, <JoinType.RIGHT: 'right'>, <JoinType.CROSS: 'cross'>]

In [44]:
from dbrepo.api.dto import QueryDefinition, JoinDefinition, ConditionalDefinition, JoinType

test_query = QueryDefinition(
    columns=[
        "participants.participant_id",
        "participants.age",
        "genders.gender_name"
    ],
    datasources=[
        "participants"
    ],
    joins=[
        JoinDefinition(
            type=JoinType.INNER,
            datasource="genders",
            conditionals=[
                ConditionalDefinition(
                    column="participants.gender_id",
                    foreign_column="genders.gender_id"
                )
            ]
        )
    ]
)

test_view = client.create_view(
    database_id=DATABASE_ID,
    name="vw_participants_gender_test",
    query=test_query,
    is_public=True,
    is_schema_public=True
)

print(test_view)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [45]:
database = client.get_database(DATABASE_ID)

print("tables:", len(database.tables))
for table in database.tables:
    print(table.name, table.internal_name, len(table.columns))

tables: 8
health_metrics health_metrics 4
lifestyle_metrics lifestyle_metrics 5
coffee_consumption coffee_consumption 3
sleep_metrics sleep_metrics 3
participants participants 5
occupations occupations 2
genders genders 2
countries countries 2

In [46]:
views = client.get_views(DATABASE_ID)

for view in views:
    print(view.id, view.name)

49246fd3-4515-48c1-b23a-fe183deea81c vw_productivity_features

In [47]:
VIEW_ID = "49246fd3-4515-48c1-b23a-fe183deea81c"

view_count = client.get_view_data_count(
    database_id=DATABASE_ID,
    view_id=VIEW_ID
)

print(view_count)

100

In [48]:
view_data = client.get_view_data(
    database_id=DATABASE_ID,
    view_id=VIEW_ID
)

print(view_data[:5])

MalformedError: Failed to get view data: {"status":"BAD_REQUEST","message":"Malformed query: [TASK_WRITE_FAILED] Task failed while writing rows to s3a://dbrepo/ec0691b7-c046-436e-aefa-1d819d76239f. SQLSTATE: 58030","code":"error.query.invalid"}

In [49]:
view_data = client.get_view_data(
    database_id=DATABASE_ID,
    view_id=VIEW_ID,
    page=0,
    size=5
)

display(view_data)

MalformedError: Failed to get view data: {"status":"BAD_REQUEST","message":"Malformed query: [TASK_WRITE_FAILED] Task failed while writing rows to s3a://dbrepo/e6a7d227-ed6b-4b2e-aee3-768def4be705. SQLSTATE: 58030","code":"error.query.invalid"}

## DBRepo View Verification Note

The DBRepo view `vw_productivity_features` was created successfully and `get_view_data_count` returned 100 rows.

Retrieving the view rows through `get_view_data` failed with a DBRepo service side error:

`TASK_WRITE_FAILED ... writing rows to s3a://dbrepo`

This indicates that the view query is valid, but the DBRepo test instance failed while exporting or materializing the result rows. The count endpoint was therefore used as the verification step.

## Final DBRepo Limitation and Subset Decision

Because DBRepo returned server side errors during bulk upload and view row retrieval, the experiment was continued with a DBRepo validation subset of 100 rows. This decision follows the course forum guidance where lecturers confirmed that continuing with a subset is acceptable when DBRepo fails due to server side limitations.

The DBRepo schema, row based data loading, and view count verification were successfully demonstrated. The complete local experiment remains available in the repository using the full processed dataset.